server:
  port: 8888

spring:
  security:
    user:
      name: stefan
      password: test
      roles: user

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

springdoc:
  swagger-ui:
    csrf:
      enabled: true